### ISSUE TITLE
Menu Items Not Found (mobile)

### ISSUE THREAD

**Issue by MrComputron** [chrisgurney/obsidian-note-toolbar#112]
**Description of the bug**
When selecting a menu item toolbar an error pops up "Check toolbar settings. Menu toolbar not found: <menu item name>"

**Steps to reproduce**

1. Have menu type toolbar item.
2. Click on it

**Expected behavior**

Should open drop down menu with the sub-toolbar items.

Bug only affects menu item types, not single command toolbar items to my knowledge.

I have only tested on mobile but will add detail when I can try on desktop.

**Screenshots (if you think it will help)**
_Video or a GIF would be appreciated._

https://github.com/user-attachments/assets/f74c5ea3-3413-4796-9d8b-a34dffb9bfdb

**Debug info:**
_Run "Show debug info" in Obsidian and paste it here (recommended). Alternately, fill out the sections below._

**Plugin, Theme links, and CSS snippets (if applicable):**
_Plugins, themes, and CSS snippets can affect the display of the toolbar. Include any being used here to help diagnose display issues._

**Desktop environment:**
 - OS: 
 - Obsidian version: 
 - Note Toolbar version: 

**Mobile environment (if applicable to the issue):**
 - Device: 
 - OS: 
 - Obsidian version: 
 - Note Toolbar version: 

**Additional context**
_Add any other context about the problem here._

**Comment by MrComputron** [comment]
I have just checked and the same issue is on desktop application.

**Comment by chrisgurney** [comment]
@MrComputron Thank you for being brave and trying out the beta.

At first I thought the migration didn't run but it seems like your toolbars are rendering correctly otherwise. (Thank you for the video.)

Are you able to edit the `data.json` file for Note Toolbar? If so we can try changing the "version" back to 20240426.1 and restart Obsidian, so the migration runs again.

Failing that would you at all mind sending your `data.json` file to me? If you have the original (pre-beta) that would amazing, actually.

**Comment by MrComputron** [comment]
Reverting to the previous version did the trick! I unfortunately didn't save a copy previous to the save but this has fixed it for the time being.

**Comment by chrisgurney** [comment]
> Reverting to the previous version did the trick! I unfortunately didn't save a copy previous to the save but this has fixed it for the time being.

Thank goodness. OK, I have a thought as to what it might be. I'll update it for the next beta.

**Comment by chrisgurney** [comment]
Crossing my fingers this is now fixed in [`1.10.0-beta-05`](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.10.0-beta-05)

**Comment by chrisgurney** [comment]
@MrComputron  I've also changed the error message to the following, in case it helps:
> `Check settings for this menu item. Toolbar not found: "..."`

Does this make sense to you?

**Comment by MrComputron** [comment]
It makes sense. Only thing I would suggest would be to consider specifying Note Toolbar settings instead of a general "settings".

**Comment by chrisgurney** [comment]
@MrComputron I've updated the error message with your feedback. Thank you!

I'll leave this ticket here for reference in case others experience this with the beta migration.

Again, crossing my fingers this is now fixed in [1.10.0-beta-05](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.10.0-beta-05)
