### ISSUE TITLE
Box shadow appearing overtop of text

### ISSUE THREAD

**Issue by chrisgurney** [chrisgurney/obsidian-note-toolbar#90]
### Discussed in https://github.com/chrisgurney/obsidian-note-toolbar/discussions/88

<div type='discussions-op-text'>

<sup>Originally posted by **XMB-7** June 22, 2024</sup>
Currently when applied `border` or even `no-border`, the border always exists, so sometimes it looks like a strikethrough.
Maybe a 100% transparent border would help to prevent this.

![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/65625632/4e9303cf-ae3d-4db8-8862-be99e9e068a8)

</div>

**Comment by chrisgurney** [comment]
Note to self: Two commits to look at when I'm able to get to this:

```
% git log -L 682,682:styles.css

commit 15a3b88afb9c87b3b0e84e94875a9a96a3d608d4
Author: Chris Gurney <chris@chrisgurney.ca>
Date:   Wed Apr 17 22:20:11 2024 -0400

    fix: missed Style Settings plugin color in container box-shadow

diff --git a/styles.css b/styles.css
--- a/styles.css
+++ b/styles.css
@@ -450,1 +450,1 @@
-    box-shadow: 0 0 0 1px var(--background-primary);
+    box-shadow: 0 0 0 1px var(--cg-nt-tbar-bg-color);

commit b0b7cd0d94401eada1666e8eb0b536a78f354a3f
Author: Chris Gurney <chris@chrisgurney.ca>
Date:   Tue Mar 26 06:07:10 2024 -0400

    fix: callout hover box-shadow past edges of sticky toolbar

diff --git a/styles.css b/styles.css
--- a/styles.css
+++ b/styles.css
@@ -303,0 +300,1 @@
+    box-shadow: 0 0 0 1px var(--background-primary);
```

**Comment by chrisgurney** [comment]
@XMB-7 Can you confirm if this is specific for you to `autohide`? I thought I knew what the problem was but now I'm not sure. I'm investigating.

**Comment by chrisgurney** [comment]
@XMB-7 if this is specific to `autohide` toolbars, try out [1.9.5](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.9.5) and let me know how it works for you.

**Comment by XMB-7** [comment]
Thanks for your time and effort. It works well. However, I think that binding this feature to `no-border` instead of `autohide` would be more relevant.

Before fixing:
![recording](https://github.com/user-attachments/assets/77990db9-f4ae-40ba-a520-3f00a8e1d8df)

After fixing:
![recording](https://github.com/user-attachments/assets/e1d34ee9-477b-4db1-98c5-308dca86d772)

**Comment by chrisgurney** [comment]
@XMB-7 Thanks for confirming!

Regarding your comment, the particular `box-shadow` that was an issue here was meant to fill in a gap around the toolbar, and just used the background color to do so. It just wasn't honoring the transparency of the `autohide` property, and was not necessary to show if the toolbar's hidden. 

I'll close this issue as it sounds like it did solve the underlying problem. Thanks again for logging it and testing!

**Comment by XMB-7** [comment]
Sorry that I didn't describe the problem precisely, since I have little knowledge on CSS. What I really mean is that without `autohide` the demand still exists.

With the following style settings, the problem also occurs.
<img src="https://github.com/user-attachments/assets/70b9c465-4c16-44cd-854b-971b4ce37836" width='300'></img>
<img src="https://github.com/user-attachments/assets/b288c26d-6255-49fd-920f-bb65681e09bb" width='400'></img>

The same when
<img src="https://github.com/user-attachments/assets/6368131e-efce-41bc-ba43-37ee93e4d8e6" width='300'></img>
<img src="https://github.com/user-attachments/assets/2e98746d-f882-45af-877d-1adb1067ab3b" width='400'></img>

So I think the modification on `autohide` should be migrated to `sticky` when combined with `border`/`no-border`.
Since if only `autohide` selected without `sticky`, when scrolling down the toolbar never shows up, then there is no issue at all. 
<img src="https://github.com/user-attachments/assets/8dbbe0d2-e98d-4f55-b20d-0b5bcb82cf88" width='300'></img>
<img src="https://github.com/user-attachments/assets/3f135e89-c82d-4c8e-87c0-989d4a3d5655" width='400'></img>

**Comment by chrisgurney** [comment]
Okay I'll take a look. 

On further thought, I believe the `box-shadow` change should only be made to apply to the bottom, not all the way around.

**Comment by chrisgurney** [comment]
@XMB-7 Thanks for your patience.I just removed that box-shadow in the latest release -- I honestly can't recall why it was there in the first place, even after re-reading my comments; hopefully doesn't bring up any regressions. 

Anybody reading this can use [Style Settings](https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Style-Settings-plugin-support) to adjust padding and such if needed.
